### ISSUE TITLE
A gun hitting a creature while crouching does not deal damage but hitting the creature in the head does

### ISSUE THREAD

**Issue by fzrdwa123456** [mchhui/MWF-SHINING#38]
https://github.com/mchhui/MWF-SHINING/assets/130232431/3ed19a22-e82f-4a80-8fac-8d83a3a70f84

**Comment by fzrdwa123456** [comment]
Versions 2.4.4f-fix2

**Comment by mchhui** [comment]
Fixed 已修复 https://github.com/mchhui/MWF-SHINING/commit/91bf7d358134f62e67a916b2b681a3f83d0a874f
